### ISSUE TITLE
port to py3 ?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [odysseus9672/SELPythonLibs#2]
I'm trying to us your SigFigRounding.py code, and ran into an issue with:

`NameError: name 'long' is not defined`

python3 no longer has a long type -- that's easy to fix, but there may be other issues -- just thought I'd let you know.

**Comment by odysseus9672** [comment]
I just pushed a fix that should address this issue. I also fixed an unrelated bug. Thanks!
