### ISSUE TITLE
Bug with specific value?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [odysseus9672/SELPythonLibs#3]
I'll start with "floating point is hard!" -- I'm confused about all this, but I'm getting a result that seems to be not-quite right:

```
In [18]: x
Out[18]: 3.3456789e-20

In [19]: sig
Out[19]: 4

In [20]: RoundToSigFigs_fp(x, sig)
Out[20]: 3.3459999999999996e-20
```

I was hoping for `3.346e20`

I understand that the result is *almost* as close as you can get to the expected value in binary.

However, if IIUC, Python will present a round decimal value when the binary value is as close as you can get to a round decimal value, and there *is* a binary value that is closer to the decimal value I'm expecting, hence:

```
In [24]: repr(3.346e-20)
Out[24]: '3.346e-20'
```
So I'm hoping that a round-to-decimal-sigfigs function would produce the closest possible value to the decimal one, but:

```
In [25]: 3.346e-20 - RoundToSigFigs_fp(x, sig)
Out[25]: 6.018531076210112e-36
```

and

```
In [31]: math.isclose(3.346e-20, RoundToSigFigs_fp(x, sig), rel_tol=1e-15)
Out[31]: True
```

but:

```In [32]: math.isclose(3.346e-20, RoundToSigFigs_fp(x, sig), rel_tol=1e-16)
Out[32]: False
```

It's off in about the 16th decimal digit -- i.e. probably the last bit or two in binary. Which for computation purposes doesn't matter, but it does mean that display doesn't get what we want, and I *think* the use case for sigfigs is pretty much about display / representation in decimal format.

In my case, I'm using it to round values that will be written to JSON -- but I'm not in control of how the JSON formatter rounds, so I want to pass rounded numbers that will be rounded when the default `repr()` (or `str()`?)  is used.

Honestly, I haven't taken the time to properly understand how your code works, and it does work as I expect for all the other values I've tested -- I just arbitrarily landed on this one in a test.

NOTE: a far more trivial approach works as I expect:

```
In [34]: x
Out[34]: 3.3456789e-20

In [35]: np.round(x, sig - int(np.floor(np.log10(np.abs(x)))) - 1)
Out[35]: 3.346e-20
```

As does using the g formatter:

```
In [39]: float(f"{x:.4g}")
Out[39]: 3.346e-20
```

I'm honestly not sure what the advantage of your approach is -- but you put so much thought into it, I assume it's for good reason :-)

**Comment by odysseus9672** [comment]
That is, indeed, a limitation of floating point. Most of the functions in this library are intended to be fast by avoiding taking any logarithms. This optimization may be considered frivolous, but I found it to be an interesting exercise. If you want exact rounding you'll want to use the function `RoundToSigFigs_decim`, but if you convert floating point values to decimal it will likely produce the same problem. 

The functions that are most close to doing what you want are the ones that begin with `Format`, since they output strings. You're also right that much of this functionality can be accomplished with careful use of "round" and python's formatting functions. The primary use for the library that is actually unique is in `ValueWithUncsRounding`, which correctly handles rounding for values combined with their uncertainties.

As a side note, I updated the testing code, and have found that rounding 0.5555 to three sig figs makes an interesting test case. As a decimal number, this should round to 0.556, but blindly using floating point would produce 0.555 (because float(0.5555) < 0.5555). The floating point algorithm in this library somehow produces 0.556, though. I think this behavior is tolerable, since floating point operations are inherently understood to be inexact, and this result happens to be more accurate than expected.

**Comment by ChrisBarker-NOAA** [comment]
> If you want exact rounding you'll want to use the function RoundToSigFigs_decim, but if you convert floating point values to decimal it will likely produce the same problem.

Maybe not -- if you convert to exact decimal, then to float, it should give the same result as converting from a decimal string. But then there's not a lot of performance advantage.

> The functions that are most close to doing what you want are the ones that begin with Format, since they output strings.

I should take another look, but then again, if I want strings, I can use the "g" formatter. The folks that wrote libc surely know what they are doing :-) In fact, for the problem at hand, I ended up punting and passing it through a string with g format specifier -- that does provide consistent results, which I had a really hard time getting any other way.

Anyway -- interesting work, thanks for putting it out there.

**Comment by ChrisBarker-NOAA** [comment]
Another thought: internally, the Decimal type must be storing the mantissa in decimal -- too bad there doesn't appear to be any way to access it directly :-(

**Comment by odysseus9672** [comment]
You can, you would just need to go straight from string to Decimal without first using any floating point type.

**Comment by ChrisBarker-NOAA** [comment]
You can? How? I can't see a way.

IIUC, Decimal, under the hood is storing a mantissa and exponent, in decimal integers. Which means that the mantissa is there, and for the problem at hand, you could then simply round the mantissa to the number of significant figures you want (and adjust the exponent). But only if you can get and set the mantissa directly, which I don't think we have access to (unless using the C API). :-( It's kind of a shame, actually, as wouldn't that be one point have having a decimal type in the first place?

It turns out that there *is* a `_pydecimal` module that does expose the mantissa and exponent directly:

https://github.com/python/cpython/blob/main/Lib/_pydecimal.py

The mantissa is actually stored as a string, so you can write a quickie sigfigs converter like so:

```
In [196]: def sigfigs_pydecimal(num_str, sigfig):
     ...:     from _pydecimal import Decimal
     ...:     d = Decimal(num_str)
     ...:     num_digits = len(d._int)
     ...:     i = round(int(d._int), - num_digits + sigfigs + 1)
     ...:     d._int = str(i)[:sigfig]
     ...:     d._exp = d._exp + (num_digits - sigfig)
     ...:     return d
     ...: 

In [197]: sigfigs_pydecimal('1.23456', 4)
Out[197]: Decimal('1.235')

In [198]: sigfigs_pydecimal('1.23456e20', 4)
Out[198]: Decimal('1.235E+20')

In [199]: sigfigs_pydecimal('1.23456e-20', 4)
Out[199]: Decimal('1.235E-20')
```
I'm sure lots of edge cases aren't handled properly, but it's an interesting exercise. 

Makes me think that this should be added to the Decimal type directly.

OK -- I'm spent way too much time on this after having solved my actual problem at hand -- thanks for engaging!
